version: "3"

services:
  model-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_PATH=/app/models/your-model.gguf
      - GPU_LAYERS=40
      - CONTEXT_LENGTH=4096
      - MAX_NEW_TOKENS=512
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
